# Generated by Django 5.0.1 on 2024-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NfcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('source_address', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=32)),
                ('temperature', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
